export const MNEMONIC_KEY = 'MNEMONIC_KEY';
export const BITCOIN_WALLET_ADDRESS = 'BITCOIN_WALLET_ADDRESS';
export const SCREEN_REMITTANCES_READY = 'SCREEN_REMITTANCES_READY';


/* SECURITY */
export const PASSPHRASE_IPFS = 'AEGIR_PASSPHRASE_IPFS';

/* Contact book */
export const CONTACT_BOOK_CID = 'AEGIR_CONTACT_BOOK_CID';
export const CONTACT_BOOK_FILENAME = 'AEGIR_CONTACT_BOOK_FILENAME';

/* Collectibles */
export const COLLECTIBLES_CID = 'AEGIR_COLLECTIBLES_CID';
export const COLLECTIBLES_FILENAME = 'AEGIR_COLLECTIBLES_FILENAME';

/* HYDRO */
export const HYDRO_ENCRYPTED_PRIVKEY = 'ENCRYPTEDKEY';
export const HYDRO_WALLET_ADDRESS = 'HYDRO_WALLET_ADDRESS';

/* TUSC */
export const TUSC_WALLET_NAME = 'TUSC_WALLET_NAME';
export const TUSC_WALLET_ADDRESS = 'TUSC_WALLET_ADDRESS';
export const TUSC_WALLET_PRIVKEY = 'TUSC_WALLET_PRIVKEY';

/* PLAY STORE / APPLE STORE */
export const APPLE_STORE_ID = 'id284882215';
export const GOOGLE_PACKAGE_NAME = 'com.aegirwallet';

/* App state manager */
export const LOCK_TIME = 'AEGIR_LOCK_TIME';
export const CUSTOM_TOKENS = 'AEGIR_CUSTOM_TOKENS';
export const LAST_BLOCK_NUMBER_BSC = 'LAST_BLOCK_NUMBER_BSC';
export const DEFAULT_FIAT_CURRENCY = 'AEGIR_DEFAULT_FIAT_CURRENCY';
export const LAST_BLOCK_NUMBER_ETHEREUM = 'LAST_BLOCK_NUMBER_ETHEREUM';
export const NOTIFICATION_CHECK_FREQUENCY_FOREGROUND = 1000 * 60; // 1 min
export const NOTIFICATION_CHECK_FREQUENCY_BACKGROUND = 1000 * 60 * 15; // 15 min