export const PASSWORD = 'PASSWORD';
export const MNEMONIC_KEY = 'MNEMONIC_KEY';
export const BITCOIN_WALLET_ADDRESS = 'BITCOIN_WALLET_ADDRESS';
export const SCREEN_REMITTANCES_READY = 'SCREEN_REMITTANCES_READY';

/* HYDRO */
export const HYDRO_ENCRYPTED_PRIVKEY = 'ENCRYPTEDKEY';
export const HYDRO_WALLET_ADDRESS = 'HYDRO_WALLET_ADDRESS';

/* TUSC */
export const TUSC_WALLET_NAME = 'TUSC_WALLET_NAME';
export const TUSC_WALLET_ADDRESS = 'TUSC_WALLET_ADDRESS';
export const TUSC_WALLET_PRIVKEY = 'TUSC_WALLET_PRIVKEY';

/* PLAY STORE / APPLE STORE */
export const APPLE_STORE_ID = 'id284882215';
export const GOOGLE_PACKAGE_NAME = 'com.aegirwallet';

/* App state manager */
export const LAST_BLOCK_NUMBER_BSC = 'LAST_BLOCK_NUMBER_BSC';
export const LAST_BLOCK_NUMBER_ETHEREUM = 'LAST_BLOCK_NUMBER_ETHEREUM';